name: game_tools_lib_example
description: "Demonstrates how to use the game_tools_lib plugin."
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  game_tools_lib:
    path: ../
  provider: ^6.1.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/images/


