name: game_tools_lib
description: "A Collection of Tools to interact with a game to create useful community tools. These should only access the Game in a legal/allowed way via image recognition and reading log files"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # default icons
  ffi: 2.1.4 # native c/c++ code
  plugin_platform_interface: 2.0.2 # platform interface not needed currently
  opencv_dart: 1.4.2+1 # image processing (IMPORTANT: when updating, rebuild libs in "build/test" folder!)
  synchronized: 3.4.0 # logging
  hive: 2.2.3 # database
  path: ^1.9.1 # files
  intl: ^0.20.2 # dates
  collection: ^1.19.1
  equatable: 2.0.7 # for entities
  provider: ^6.1.5

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      linux:
        dartPluginClass: GameToolsLib
        pluginClass: GameToolsLibPlugin
        ffiPlugin: true
      macos:
        dartPluginClass: GameToolsLib
        pluginClass: GameToolsLibPlugin
        ffiPlugin: true
      windows:
        dartPluginClass: GameToolsLib
        pluginClass: GameToolsLibPluginCApi
        ffiPlugin: true

  assets:
    - assets/
    - assets/locales/
    - assets/images/

# opencv module config
hooks:
  user_defines:
    dartcv4:
      exclude_modules:
        - contrib
        - dnn
        - features2d
        - core
      include_modules:
        - core # core is always required thus will be ignored even configured here.
        - imgproc
        - imgcodecs
        - videoio
